apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: labx
    type: proxy
  name: labx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: labx
      type: proxy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: labx
        type: proxy
    spec:
      containers:
      - image: nginx:1.9
        name: nginx
        resources: {}
status: {}

